### ISSUE TITLE
Fix encoding bugs

### ISSUE THREAD

**Issue by fatlotus** [uchicago-sg/caravel#173]
See traceback for /new:

```
Exception on /new [POST]
Traceback (most recent call last):
  File "/base/data/home/apps/s~hosted-caravel/master.388755493830229368/caravel/../vendor/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/base/data/home/apps/s~hosted-caravel/master.388755493830229368/caravel/../vendor/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/base/data/home/apps/s~hosted-caravel/master.388755493830229368/caravel/../vendor/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/base/data/home/apps/s~hosted-caravel/master.388755493830229368/caravel/../vendor/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/base/data/home/apps/s~hosted-caravel/master.388755493830229368/caravel/../vendor/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/base/data/home/apps/s~hosted-caravel/master.388755493830229368/caravel/controllers/listings.py", line 206, in new_listing
    is_valid = form.validate_on_submit()
  File "/base/data/home/apps/s~hosted-caravel/master.388755493830229368/caravel/../vendor/flask_wtf/form.py", line 156, in validate_on_submit
    return self.is_submitted() and self.validate()
  File "/base/data/home/apps/s~hosted-caravel/master.388755493830229368/caravel/controllers/forms.py", line 66, in validate
    self.post_validate()
  File "/base/data/home/apps/s~hosted-caravel/master.388755493830229368/caravel/controllers/listings.py", line 203, in <lambda>
    form.post_validate = lambda: policy.claim_listing(listing)
  File "/base/data/home/apps/s~hosted-caravel/master.388755493830229368/caravel/policy/eligible_users.py", line 117, in claim_listing
    subject="Marketplace Listing \"{}\"".format(listing.title),
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2013' in position 27: ordinal not in range(128)
```

**Comment by fatlotus** [comment]
Obligatory Profound Programmer

![](http://i.imgur.com/Jl266.jpg)
